export const GreekOptions = [
    { label: 'None', value: 'None' },
    { label: 'Pi Beta Phi', value: 'Pi Beta Phi' },
    { label: 'Alpha Phi', value: 'Alpha Phi' },
    { label: 'Delta Delta Delta', value: 'Delta Delta Delta' },
    { label: 'Kappa Alpha Theta', value: 'Kappa Alpha Theta' },
    { label: 'Gamma Phi Beta', value: 'Gamma Phi Beta' },
    { label: 'Delta Gamma', value: 'Delta Gamma' },
    { label: 'Alpha Chi Omega', value: 'Alpha Chi Omega' },
    { label: 'Kappa Kappa Gamma', value: 'Kappa Kappa Gamma' },
    { label: 'Alpha Delta Pi', value: 'Alpha Delta Pi' },
    { label: 'Chi Omega', value: 'Chi Omega' },
    { label: 'Sigma Kappa', value: 'Sigma Kappa' },
    { label: 'Zeta Tau Alpha', value: 'Zeta Tau Alpha' },
    { label: 'Alpha Gamma Delta', value: 'Alpha Gamma Delta' },
    { label: 'Delta Zeta', value: 'Delta Zeta' },
    { label: 'Alpha Xi Delta', value: 'Alpha Xi Delta' },
    { label: 'Delta Phi Epsilon', value: 'Delta Phi Epsilon' },
    { label: 'Alpha Omicron Pi', value: 'Alpha Omicron Pi' },
    { label: 'Gamma Phi Beta', value: 'Gamma Phi Beta' },
    { label: 'Phi Sigma Sigma', value: 'Phi Sigma Sigma' },
    { label: 'Sigma Delta Tau', value: 'Sigma Delta Tau' },
    { label: 'Alpha Sigma Alpha', value: 'Alpha Sigma Alpha' },
    { label: 'Alpha Epsilon Phi', value: 'Alpha Epsilon Phi' },
    { label: 'Alpha Phi Gamma', value: 'Alpha Phi Gamma' },
    { label: 'Beta Sigma Phi', value: 'Beta Sigma Phi' },
    { label: 'Delta Phi Lambda', value: 'Delta Phi Lambda' },
    { label: 'Gamma Sigma Sigma', value: 'Gamma Sigma Sigma' },
    { label: 'Delta Phi Mu', value: 'Delta Phi Mu' },
    { label: 'Zeta Phi Beta', value: 'Zeta Phi Beta' },
    { label: 'Sigma Gamma Rho', value: 'Sigma Gamma Rho' },
    { label: 'Alpha Kappa Alpha', value: 'Alpha Kappa Alpha' },
    { label: 'Delta Sigma Theta', value: 'Delta Sigma Theta' },
    { label: 'Zeta Phi Beta', value: 'Zeta Phi Beta' },
    { label: 'Sigma Gamma Rho', value: 'Sigma Gamma Rho' },
    { label: 'Alpha Chi Rho', value: 'Alpha Chi Rho' },
    { label: 'Alpha Delta Phi', value: 'Alpha Delta Phi' },
    { label: 'Alpha Epsilon Pi', value: 'Alpha Epsilon Pi' },
    { label: 'Alpha Gamma Rho', value: 'Alpha Gamma Rho' },
    { label: 'Alpha Kappa Lambda', value: 'Alpha Kappa Lambda' },
    { label: 'Alpha Phi Alpha', value: 'Alpha Phi Alpha' },
    { label: 'Beta Theta Pi', value: 'Beta Theta Pi' },
    { label: 'Delta Chi', value: 'Delta Chi' },
    { label: 'Delta Kappa Epsilon', value: 'Delta Kappa Epsilon' },
    { label: 'Delta Sigma Phi', value: 'Delta Sigma Phi' },
    { label: 'Iota Phi Theta', value: 'Iota Phi Theta' },
    { label: 'Kappa Alpha Order', value: 'Kappa Alpha Order' },
    { label: 'Kappa Alpha Psi', value: 'Kappa Alpha Psi' },
    { label: 'Lambda Chi Alpha', value: 'Lambda Chi Alpha' },
    { label: 'Phi Beta Sigma', value: 'Phi Beta Sigma' },
    { label: 'Phi Delta Theta', value: 'Phi Delta Theta' },
    { label: 'Phi Gamma Delta (FIJI)', value: 'Phi Gamma Delta (FIJI)' },
    { label: 'Phi Kappa Psi', value: 'Phi Kappa Psi' },
    { label: 'Phi Kappa Sigma', value: 'Phi Kappa Sigma' },
    { label: 'Phi Kappa Tau', value: 'Phi Kappa Tau' },
    { label: 'Phi Sigma Kappa', value: 'Phi Sigma Kappa' },
    { label: 'Pi Kappa Alpha', value: 'Pi Kappa Alpha' },
    { label: 'Pi Kappa Phi', value: 'Pi Kappa Phi' },
    { label: 'Psi Upsilon', value: 'Psi Upsilon' },
    { label: 'Sigma Alpha Epsilon', value: 'Sigma Alpha Epsilon' },
    { label: 'Sigma Alpha Mu', value: 'Sigma Alpha Mu' },
    { label: 'Sigma Chi', value: 'Sigma Chi' },
    { label: 'Sigma Nu', value: 'Sigma Nu' },
    { label: 'Sigma Phi Epsilon', value: 'Sigma Phi Epsilon' },
    { label: 'Sigma Pi', value: 'Sigma Pi' },
    { label: 'Tau Kappa Epsilon', value: 'Tau Kappa Epsilon' },
    { label: 'Theta Chi', value: 'Theta Chi' },
    { label: 'Theta Delta Chi', value: 'Theta Delta Chi' },
    { label: 'Theta Xi', value: 'Theta Xi' },
    { label: 'Zeta Beta Tau', value: 'Zeta Beta Tau' },
    { label: 'Alpha Kappa Brolic', value: 'Alpha Kappa Brolic' }
];

export const Locations = [
    { label: 'Gainesville, Florida', value: {Latitude:29.651634, Longitude:-82.324829} },

];


export const Genders = [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Other', value: 'Other' },
];

export const GenderPreferences = [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Both', value: 'Both' },
    { label: 'Other', value: 'Other' },
];

export const Height = [
    { label: "3'0", value: "3'0" },
    { label: "3'1", value: "3'1" },
    { label: "3'2", value: "3'2" },
    { label: "3'3", value: "3'3" },
    { label: "3'4", value: "3'4" },
    { label: "3'5", value: "3'5" },
    { label: "3'6", value: "3'6" },
    { label: "3'7", value: "3'7" },
    { label: "3'8", value: "3'8" },
    { label: "3'9", value: "3'9" },
    { label: "3'10", value: "3'10" },
    { label: "3'11", value: "3'11" },
    { label: "4'0", value: "4'0" },
    { label: "4'1", value: "4'1" },
    { label: "4'2", value: "4'2" },
    { label: "4'3", value: "4'3" },
    { label: "4'4", value: "4'4" },
    { label: "4'5", value: "4'5" },
    { label: "4'6", value: "4'6" },
    { label: "4'7", value: "4'7" },
    { label: "4'8", value: "4'8" },
    { label: "4'9", value: "4'9" },
    { label: "4'10", value: "4'10" },
    { label: "4'11", value: "4'11" },
    { label: "5'0", value: "5'0" },
    { label: "5'1", value: "5'1" },
    { label: "5'2", value: "5'2" },
    { label: "5'3", value: "5'3" },
    { label: "5'4", value: "5'4" },
    { label: "5'5", value: "5'5" },
    { label: "5'6", value: "5'6" },
    { label: "5'7", value: "5'7" },
    { label: "5'8", value: "5'8" },
    { label: "5'9", value: "5'9" },
    { label: "5'10", value: "5'10" },
    { label: "5'11", value: "5'11" },
    { label: "6'0", value: "6'0" },
    { label: "6'1", value: "6'1" },
    { label: "6'2", value: "6'2" },
    { label: "6'3", value: "6'3" },
    { label: "6'4", value: "6'4" },
    { label: "6'5", value: "6'5" },
    { label: "6'6", value: "6'6" },
    { label: "6'7", value: "6'7" },
    { label: "6'8", value: "6'8" },
    { label: "6'9", value: "6'9" },
    { label: "6'10", value: "6'10" },
    { label: "6'11", value: "6'11" },
    { label: "7'0", value: "7'0" },
    { label: "7'1", value: "7'1" },
    { label: "7'2", value: "7'2" },
    { label: "7'3", value: "7'3" },
    { label: "7'4", value: "7'4" },
    { label: "7'5", value: "7'5" },
    { label: "7'6", value: "7'6" },
    { label: "7'7", value: "7'7" },
    { label: "7'8", value: "7'8" },
  ];  

  export const Hobbies = [
    'Reading',
    'Fitness',
    'Traveling',
    'Movies',
    'Writing',
    'Football',
    'Volleyball',
    'Soccer',
    'Sports',
    'Jewlery',
    'Gambling',
    'BlackJack',
    'Basketball',
    'Baseball',
    'Kickball',
    'SoftBall',
    'Running',
    'Swimming',
    'Painting',
    'Driving',
    'Sculpting',
    'Cooking',
    'Partying',
    'Baking',
    'Gardening',
    'Photography',
    'Music',
    'Singing',
    'Dancing',
    'Hiking',
    'Camping',
    'Clubing',
    'Fishing',
    'Birdwatching',
    'Knitting',
    'Crocheting',
    'Sewing',
    'Pottery',
    'Meditation',
    'Yoga',
    'Chess',
    'Board games',
    'Video games',
    'Coding',
    'Blogging',
    'Volunteering',
    'Scuba diving',
    'Drawing',
    'Skydiving',
    'Surfing',
    'Skiing',
    'Snowboarding',
    'Rock climbing',
    'Mountain biking',
    'Kayaking',
    'Canoeing',
    'Paragliding',
    'Paintball',
    'Shopping',
    'Archery',
    'Horseback riding',
    'Sailing',
    'Videography',
    'Astrology',
    'Stargazing',
    'Thrifting',
    'Collecting',
    'Calligraphy',
    'Origami',
    'Beekeeping',
    'Candle making',
    'Embroidery',
    'Metalworking',
    'Leathercraft',
    'Woodworking',
    'Scrapbooking',
    'Quilting',
    'Cross-stitching',
    'Glassblowing',
    'Wine tasting',
    'Beer brewing',
    'Tea tasting',
    'Coffee roasting',
    'Mixology',
    'Fermentation',
    'Pickling',
    'Urban gardening',
    'Aquascaping',
    'Model building',
    'Geocaching',
    'Metal detecting',
    'Parkour',
    'Juggling',
    'Magic tricks',
    'Puppetry',
    'Beach',
    'Beatboxing'
];