export const GreekOptions = [
    { label: 'None', value: 'None' },
    { label: 'Pi Beta Phi', value: 'Pi Beta Phi' },
    { label: 'Alpha Phi', value: 'Alpha Phi' },
    { label: 'Delta Delta Delta', value: 'Delta Delta Delta' },
    { label: 'Kappa Alpha Theta', value: 'Kappa Alpha Theta' },
    { label: 'Gamma Phi Beta', value: 'Gamma Phi Beta' },
    { label: 'Delta Gamma', value: 'Delta Gamma' },
    { label: 'Alpha Chi Omega', value: 'Alpha Chi Omega' },
    { label: 'Kappa Kappa Gamma', value: 'Kappa Kappa Gamma' },
    { label: 'Alpha Delta Pi', value: 'Alpha Delta Pi' },
    { label: 'Chi Omega', value: 'Chi Omega' },
    { label: 'Sigma Kappa', value: 'Sigma Kappa' },
    { label: 'Zeta Tau Alpha', value: 'Zeta Tau Alpha' },
    { label: 'Alpha Gamma Delta', value: 'Alpha Gamma Delta' },
    { label: 'Delta Zeta', value: 'Delta Zeta' },
    { label: 'Alpha Xi Delta', value: 'Alpha Xi Delta' },
    { label: 'Delta Phi Epsilon', value: 'Delta Phi Epsilon' },
    { label: 'Alpha Omicron Pi', value: 'Alpha Omicron Pi' },
    { label: 'Gamma Phi Beta', value: 'Gamma Phi Beta' },
    { label: 'Phi Sigma Sigma', value: 'Phi Sigma Sigma' },
    { label: 'Sigma Delta Tau', value: 'Sigma Delta Tau' },
    { label: 'Alpha Sigma Alpha', value: 'Alpha Sigma Alpha' },
    { label: 'Alpha Epsilon Phi', value: 'Alpha Epsilon Phi' },
    { label: 'Alpha Phi Gamma', value: 'Alpha Phi Gamma' },
    { label: 'Beta Sigma Phi', value: 'Beta Sigma Phi' },
    { label: 'Delta Phi Lambda', value: 'Delta Phi Lambda' },
    { label: 'Gamma Sigma Sigma', value: 'Gamma Sigma Sigma' },
    { label: 'Delta Phi Mu', value: 'Delta Phi Mu' },
    { label: 'Zeta Phi Beta', value: 'Zeta Phi Beta' },
    { label: 'Sigma Gamma Rho', value: 'Sigma Gamma Rho' },
    { label: 'Alpha Kappa Alpha', value: 'Alpha Kappa Alpha' },
    { label: 'Delta Sigma Theta', value: 'Delta Sigma Theta' },
    { label: 'Zeta Phi Beta', value: 'Zeta Phi Beta' },
    { label: 'Sigma Gamma Rho', value: 'Sigma Gamma Rho' },
    { label: 'Alpha Chi Rho', value: 'Alpha Chi Rho' },
    { label: 'Alpha Delta Phi', value: 'Alpha Delta Phi' },
    { label: 'Alpha Epsilon Pi', value: 'Alpha Epsilon Pi' },
    { label: 'Alpha Gamma Rho', value: 'Alpha Gamma Rho' },
    { label: 'Alpha Kappa Lambda', value: 'Alpha Kappa Lambda' },
    { label: 'Alpha Phi Alpha', value: 'Alpha Phi Alpha' },
    { label: 'Beta Theta Pi', value: 'Beta Theta Pi' },
    { label: 'Delta Chi', value: 'Delta Chi' },
    { label: 'Delta Kappa Epsilon', value: 'Delta Kappa Epsilon' },
    { label: 'Delta Sigma Phi', value: 'Delta Sigma Phi' },
    { label: 'Iota Phi Theta', value: 'Iota Phi Theta' },
    { label: 'Kappa Alpha Order', value: 'Kappa Alpha Order' },
    { label: 'Kappa Alpha Psi', value: 'Kappa Alpha Psi' },
    { label: 'Lambda Chi Alpha', value: 'Lambda Chi Alpha' },
    { label: 'Phi Beta Sigma', value: 'Phi Beta Sigma' },
    { label: 'Phi Delta Theta', value: 'Phi Delta Theta' },
    { label: 'Phi Gamma Delta (FIJI)', value: 'Phi Gamma Delta (FIJI)' },
    { label: 'Phi Kappa Psi', value: 'Phi Kappa Psi' },
    { label: 'Phi Kappa Sigma', value: 'Phi Kappa Sigma' },
    { label: 'Phi Kappa Tau', value: 'Phi Kappa Tau' },
    { label: 'Phi Sigma Kappa', value: 'Phi Sigma Kappa' },
    { label: 'Pi Kappa Alpha', value: 'Pi Kappa Alpha' },
    { label: 'Pi Kappa Phi', value: 'Pi Kappa Phi' },
    { label: 'Psi Upsilon', value: 'Psi Upsilon' },
    { label: 'Sigma Alpha Epsilon', value: 'Sigma Alpha Epsilon' },
    { label: 'Sigma Alpha Mu', value: 'Sigma Alpha Mu' },
    { label: 'Sigma Chi', value: 'Sigma Chi' },
    { label: 'Sigma Nu', value: 'Sigma Nu' },
    { label: 'Sigma Phi Epsilon', value: 'Sigma Phi Epsilon' },
    { label: 'Sigma Pi', value: 'Sigma Pi' },
    { label: 'Tau Kappa Epsilon', value: 'Tau Kappa Epsilon' },
    { label: 'Theta Chi', value: 'Theta Chi' },
    { label: 'Theta Delta Chi', value: 'Theta Delta Chi' },
    { label: 'Theta Xi', value: 'Theta Xi' },
    { label: 'Zeta Beta Tau', value: 'Zeta Beta Tau' },
    { label: 'Alpha Kappa Brolic', value: 'Alpha Kappa Brolic' }
];

export const Locations = [
    { label: 'Gainesville, Florida', value: {Latitude:29.651634, Longitude:-82.324829} },

];


export const Genders = [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Other', value: 'Other' },
];

export const GenderPreferences = [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Both', value: 'Both' },
    { label: 'Other', value: 'Other' },
];


export const Hobbies = [
    { label: 'Reading', value: 'Reading' },
    { label: 'Fitness', value: 'Fitness' },
    { label: 'Traveling', value: 'Traveling' },
    { label: 'Movies', value: 'Movies' },
    { label: 'Writing', value: 'Writing' },
    { label: 'Football', value: 'Football' },
    { label: 'Soccer', value: 'Soccer' },
    { label: 'Basketball', value: 'Basketball' },
    { label: 'Swimming', value: 'Swimming' },
    { label: 'Painting', value: 'Painting' },
    { label: 'Drawing', value: 'Drawing' },
    { label: 'Sculpting', value: 'Sculpting' },
    { label: 'Cooking', value: 'Cooking' },
    { label: 'Patying', value: 'Partying' },
    { label: 'Baking', value: 'Baking' },
    { label: 'Gardening', value: 'Gardening' },
    { label: 'Photography', value: 'Photography' },
    { label: 'Music', value: 'Music' },
    { label: 'Singing', value: 'Singing' },
    { label: 'Dancing', value: 'Dancing' },
    { label: 'Hiking', value: 'Hiking' },
    { label: 'Camping', value: 'Camping' },
    { label: 'Fishing', value: 'Fishing' },
    { label: 'Birdwatching', value: 'Birdwatching' },
    { label: 'Knitting', value: 'Knitting' },
    { label: 'Crocheting', value: 'Crocheting' },
    { label: 'Sewing', value: 'Sewing' },
    { label: 'Pottery', value: 'Pottery' },
    { label: 'Meditation', value: 'Meditation' },
    { label: 'Yoga', value: 'Yoga' },
    { label: 'Chess', value: 'Chess' },
    { label: 'Board games', value: 'Board games' },
    { label: 'Video gaming', value: 'Video gaming' },
    { label: 'Coding', value: 'Coding' },
    { label: 'Blogging', value: 'Blogging' },
    { label: 'Volunteering', value: 'Volunteering' },
    { label: 'Scuba diving', value: 'Scuba diving' },
    { label: 'Skydiving', value: 'Skydiving' },
    { label: 'Surfing', value: 'Surfing' },
    { label: 'Skiing', value: 'Skiing' },
    { label: 'Snowboarding', value: 'Snowboarding' },
    { label: 'Rock climbing', value: 'Rock climbing' },
    { label: 'Mountain biking', value: 'Mountain biking' },
    { label: 'Kayaking', value: 'Kayaking' },
    { label: 'Canoeing', value: 'Canoeing' },
    { label: 'Paragliding', value: 'Paragliding' },
    { label: 'Paintball', value: 'Paintball' },
    { label: 'Archery', value: 'Archery' },
    { label: 'Horseback riding', value: 'Horseback riding' },
    { label: 'Sailing', value: 'Sailing' },
    { label: 'Photography', value: 'Photography' },
    { label: 'Videography', value: 'Videography' },
    { label: 'Astrology', value: 'Astrology' },
    { label: 'Stargazing', value: 'Stargazing' },
    { label: 'Thrifting', value: 'Thrifting' },
    { label: 'Collecting', value: 'Collecting' },
];
